Make all default return of photo URLs to be empty string
timwangmusic/Vacation-Planner pull request #335
Opened 2023-10-29 15:29 UTC by rwangsc18

## Description
Make all default return of photo URLs to be empty string

## Solution
* Align all return values to be an empty string when failed processing happens 

## Testing
- [ ] Integration testing on Heroku staging
- [ ] Added new unit tests

## Checks
- [x] Have you removed commented code?
- [x] Have you used gofmt to format your code?

2023-10-29 15:32 UTC, rwangsc18 commented
I also looked into how to serve a default icon/picture. Do we have example like that in this codebase?

2023-10-29 16:31 UTC, timwangmusic commented
> I also looked into how to serve a default icon/picture. Do we have example like that in this codebase? 

We are serving icons in the planning results right?

2023-10-29 18:04 UTC, timwangmusic requested changes
If we return empty strings, how would the front-end render them? I think a better mitigation is to use a default picture when we cannot get the photos. In that case, this function should return an error as the last returning value.

2023-10-30 19:46 UTC, rwangsc18 commented
> If we return empty strings, how would the front-end render them? I think a better mitigation is to use a default picture when we cannot get the photos. In that case, this function should return an error as the last returning value.

I was thinking along the same line. I have found some example like this for HTML to use a local image (checked in repo), but it does not work right away. I also searched the codebase and can't find a similar example.

2023-11-12 19:32 UTC, closed without merging