Dark mode
timwangmusic/Vacation-Planner pull request #382
Opened 2024-06-16 15:13 UTC by sananand007

## Description
Enabling Dark Mode for unwind.dev

## Solution
* Describe your code changes in detail for reviewers as well as documentation purposes. 
* For bug fixes, explain the solutions and how they fix the issues.
* For new features, describe the high-level ideas.

## Testing
- [ ] Integration testing on Heroku staging
- [ ] Added new unit tests

## Checks
- [ ] Have you removed commented code?
- [ ] Have you used gofmt to format your code?

2024-08-18 16:02 UTC, timwangmusic commented on assets/js/mode-switch.js
> +document.querySelector('#theme-switcher').addEventListener('click', switchTheme)
Add white space please

2024-09-02 00:28 UTC, timwangmusic commented on assets/templates/login_page.html
> +    <script>
Please refactor and put these in a separate file

2024-09-03 18:02 UTC, timwangmusic requested changes
Minor changes are required

2024-09-03 18:02 UTC, timwangmusic commented on assets/templates/user_profile.html
> +    <div class="container" id="user-profile-container">
So we use this ID somewhere?

2024-09-03 18:02 UTC, timwangmusic commented on assets/templates/user_profile.html
> +    <script
I don't think this change is needed.

2024-09-03 18:02 UTC, timwangmusic commented on test/redis_client_mocks/nearby_search_test.go
> +		t.Errorf("RedisClient error #{err.Error()}")
Use %s as format directive

2024-09-15 14:32 UTC, sananand007 commented on assets/js/local-storage-theme-check.js
> +function checkTheme() {
remove this file, not really needed anymore

2024-09-15 14:33 UTC, sananand007 commented on assets/templates/user_profile.html
> +    <div class="container" id="user-profile-container">
yes in style.css

2024-09-15 14:53 UTC, timwangmusic approved these changes
LGTM! Nice work

2024-09-15 14:53 UTC, timwangmusic commented on assets/templates/about.html
> +    class="inherit-line-height"
Run formatter on this file please

2024-09-15 14:55 UTC, sananand007 commented on assets/templates/user_profile.html
> +    <script
done

2024-09-15 15:04 UTC, sananand007 commented on assets/templates/about.html
> +    class="inherit-line-height"
done

2024-09-15 15:12 UTC, merged